version: "3.9"
services:
  app-ecomm:
    image: jessicammattos/ecomm:1.0
    depends_on:
      - mongo-ecomm

  mongo-ecomm:
    image: mongo
    container_name: mongo-ecomm
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: secret
    volumes:
      - db-mongo-ecomm:/data/db
    ports:
      - "27017:27017"

volumes:
  db-mongo-ecomm:
