openapi: 3.0.3
info:
  title: Ecomm
  description: Ecommerce baseado no Mercado Livre
  version: 1.0.0
servers:
  - url: http://localhost:3000
    description: API de produtos
tags:
  - name: categorias
    description: Categorias de produtos da plataforma ecomm
  - name: produtos
    description: Produtos da plataforma ecomm
paths:
  /categories:
    get:
      summary: Lista todas as Categorias
      tags:
        - categorias
      responses:
        200:
          description: Sucesso
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Categorias"
        404:
          description: Lista de categorias não encontrada
          content:
            application/json:
              example: "Not Found"
  /categories/{id}:
    parameters:
    - name: id
      in: path
      description: Identificador da categoria.
      required: true
      schema:
        type: integer
    get:
      summary: Busca uma Categoria
      tags:
        - categorias
      responses:
        200:
          description: Sucesso
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Categoria"
        404:
          description: Categoria não encontrada
          content:
            application/json:
              example: "Not Found"
  /admin/categories:
    post:
      summary: Cria uma nova Categoria de produtos
      tags:
        - categorias
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                nome:
                  type: string
      responses:
        201:
          description: Sucesso
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Categoria"
  /admin/categories/{id}:
    parameters:
    - name: id
      in: path
      description: Identificador da categoria.
      required: true
      schema:
        type: integer
    put:
      summary: Atualizar uma Categoria de produtos
      tags:
        - categorias
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                nome:
                  type: string
                status:
                  type: string
      responses:
        201:
          description: Sucesso
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Categoria"
    delete:
      summary: Remove uma Categoria de produtos
      tags:
        - categorias
      responses:
        200:
          description: Deletado com Sucesso
        404:
          description: Erro, categoria não encontrada
          content:
            application/json:
              example: "Not Found"
    patch:
      summary: Ativa uma Categoria de produtos
      tags:
        - categorias
      responses:
        200:
          description: Categoria ativa com Sucesso
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Categoria"
        404:
          description: Erro, categoria não encontrada
          content:
            application/json:
              example: "Not Found"
  /admin/products:
    post:
      summary: Cria um novo produto
      tags:
        - produtos
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Produto"
      responses:
        201:
          description: Sucesso
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Produto"
  /products:
    get:
      summary: Lista todos os Produtos
      tags:
        - produtos
      responses:
        200:
          description: Sucesso
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Produtos"
        404:
          description: Lista de produtos não encontrada
          content:
            application/json:
              example: "Not Found"
  /products/{id}:
    parameters:
    - name: id
      in: path
      description: Identificador do Produto.
      required: true
      schema:
        type: integer
    get:
      summary: Busca um Produto
      tags:
        - produtos
      responses:
        200:
          description: Sucesso
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Produto"
        404:
          description: Produto não encontrado
          content:
            application/json:
              example: "Not Found"
  /admin/products/{id}:
    parameters:
    - name: id
      in: path
      description: Identificador do Produto.
      required: true
      schema:
        type: integer
    put:
      summary: Atualizar um Produto
      tags:
        - produtos
      requestBody:
        content:
          application/json:
            schema:
                $ref: "#/components/schemas/Produto"
      responses:
        201:
          description: Sucesso
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Produto"
    delete:
      summary: Remove um Produto
      tags:
        - produtos
      responses:
        200:
          description: Deletado com Sucesso
        404:
          description: Erro, categoria não encontrada
          content:
            application/json:
              example: "Not Found"
components:
  schemas:
    Categoria:
      type: object
      properties:
        id:
          type: integer
        nome:
          type: string
        status:
          type: string
    Categorias:
      type: array
      items:
        $ref: "#/components/schemas/Categoria"
    Produto:
      type: object
      properties:
        nome:
          type: string
        descricao:
          type: string
        slug:
          type: string
        preco:
          type: number
        estoque:
          type: integer
        categoria:
          $ref: "#/components/schemas/Categoria"
    Produtos:
      type: array
      items:
        $ref: "#/components/schemas/Produto"
